# Generated by Django 3.1.1 on 2020-09-16 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instalogin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='passoward',
            new_name='password',
        ),
    ]
